[".dotfiles/oh-my-zsh"]
  type = "archive"
  url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
[".dotfiles/zsh/custom/plugins/zsh-syntax-highlighting"]
  type = "archive"
  url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
[".dotfiles/zsh/custom/themes/powerlevel10k"]
  type = "archive"
  url = "https://github.com/romkatv/powerlevel10k/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
[".dotfiles/vim"]
  type = "git-repo"
  url = "https://github.com/mingyc/vimrc.git"
  refreshPeriod = "168h"
[".dotfiles/gdb/gdbinit"]
  type = "git-repo"
  url = "https://github.com/gdbinit/Gdbinit.git"
[".config/kitty/kitty-themes/themes/Solarized_Dark_Higher_Contrast.conf"]
  type = "file"
  url = "https://raw.githubusercontent.com/dexpota/kitty-themes/master/themes/Solarized_Dark_Higher_Contrast.conf"

